first_name = input("Enter your first name: ").strip()
last_name = input("Enter your last name: ").strip()
city = input("Enter your city: ").strip()
year_of_birth = input("Enter your year of birth: ").strip()
favourite_programming_language = input("Enter your favourite programming language: ").strip()
user_id = first_name[:2] + last_name[:3] + year_of_birth[-2:]

print(f"User ID: {user_id}")
print(f"First name: {first_name}")
print(f"Last name: {last_name}")
print(f"Year of birth: {year_of_birth}")
print(f"City: {city}")
print(f"Favourite programming language: {favourite_programming_language}")
print(f"Initials: {first_name[0]}.{last_name[0]}")
print(f"Full name length: {len(first_name) + len(last_name)}")
print(f"Favourite programming language reversed: {favourite_programming_language[::-1]}")
print(f"Email address: {first_name.lower()}.{last_name.lower()}@example.com")
print(f"Final letters of name: {first_name[-1]}, {last_name[-1]}")
print(f"First two characters of year of birth: {year_of_birth[:2]}")
print(f"Uppercase city: {city.upper()}")